### ISSUE TITLE
Integrate it into the taskbar

### ISSUE THREAD

**Issue by 833M0L3** [samir-dahal/sambat-widget-landing#1]
Hey there, I just found out about your project. Pretty cool that it also shows the events of all of the dates.

It would be great if it is possible to integrate it into the taskbar for better looks and visibility of the content. 

Like this in the picture below : 

![image](https://user-images.githubusercontent.com/59522309/232278543-88c298f5-de55-4f28-9ea3-0a4ae018220d.png)

**Comment by samir-dahal** [comment]
Thanks! I'll look into it.
